entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true

providers:
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: seuemail@exemplo.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
